# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baddf16f6561c01e341d2ee960899457f9c9ebd67bd38463e481cc7dee81fc01d7e628489bc7572d273c96686d08b0fdd124a85958f4066a97a16065aad01711

test:
  secret_key_base: 866b78bf5ba12a481379de81093bac2c18d9125dfab4fc473a2807a900b4f84022d7c6d9981ee835b7aa556b236459d67bbf71d4eabc7999dcf103785452107a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
